steps:
- name: gcr.io/cloud-builders/docker
  args: [build, -f, Dockerfile.codex, -t, gcr.io/project-28d42275-7fed-43e6-a9a/ate-images/agentplane-brain-codex:x3, .]
images: [gcr.io/project-28d42275-7fed-43e6-a9a/ate-images/agentplane-brain-codex:x3]
